version: '3.8'

services:
  # This builds and runs the Python API
  backend-service:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - app-network

  # This builds and runs the Nginx Frontend
  frontend-service:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge